config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                      root GET    /                                                                                        items#index
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#                     items GET    /items(.:format)                                                                         items#index
#                           POST   /items(.:format)                                                                         items#create
#                  new_item GET    /items/new(.:format)                                                                     items#new
#                 edit_item GET    /items/:id/edit(.:format)                                                                items#edit
#                      item GET    /items/:id(.:format)                                                                     items#show
#                           PATCH  /items/:id(.:format)                                                                     items#update
#                           PUT    /items/:id(.:format)                                                                     items#update
#                           DELETE /items/:id(.:format)                                                                     items#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do

  root "items#index"
  devise_for :users
  resources :items
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id         :integer          not null, primary key
#  name       :string
#  author     :string
#  ISBN       :string
#  item_type  :integer          default("book")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  cover      :string
#

class Item < ApplicationRecord
  belongs_to :user, optional: true
  validates :name, presence: true, length: { maximum: 150 }
  validates :ISBN, length: { is: 17 }, allow_blank: true, allow_nil: true
  enum item_type: [:book, :music, :film]
  mount_uploader :cover, CoverUploader


  def self.search(search)
  	where("name LIKE ? OR author LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string           default(""), not null
#  surname                :string           default(""), not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
  	"#{self.name} #{self.surname}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	def hello
	end

	protected

    def configure_permitted_parameters
    	attributes = [:name, :surname, :email, :password, :password_confirmation]
        devise_parameter_sanitizer.permit(:sign_in, keys: attributes)
        devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def show
    @item = Item.find(params[:id])
  end
  
  def new
  	@item = Item.new
  end

  def create
  	@items = Item.all
  	@item = Item.new(item_params)
    if @item.save
      respond_to do |format|
      	format.html { redirect_to items_path }
      	format.js
      end
    else
      render 'new'
    end
  end

  def index
  	if params[:search]
  	  @items = Item.search(params[:search]).order("id").page(params[:page]).per(10)
  	else
  	  @items = Item.all.order("id").page(params[:page]).per(10)
    end
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def update
  	@item = Item.find(params[:id])
  	if @item.update_attributes(item_params)
  	  redirect_to @item
  	else
  	  render 'edit'
  	end
  end

  private

    def item_params
      params.require(:item).permit(:name, :author, :ISBN, :item_type,
      	                           :cover, :remove_cover, :search)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/application/hello.html.haml
%h1 Hello world!
- if user_signed_in?
  %h2
    Logged as #{current_user.full_name}
  = link_to "Log out", destroy_user_session_path, method: :delete
- else
  = link_to "Log in", new_user_session_path
  %br/
  = link_to "Sign up", new_user_registration_path

app/views/items/_form.html.haml
= form_for @item, id: "new_item", remote: true, html: { multipart: true } do |f|
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :author
    %br/
    = f.text_field :author
  .field
    = f.label :ISBN
    %br/
    = f.text_field :ISBN
  .field
    = f.label :item_type
    %br/
    = f.select :item_type, Item.item_types.keys.map
  .field
    = f.label :cover
    %br/
    = f.file_field :cover
    - if @item.cover?
      = image_tag @item.cover.thumb.url
      = f.label :remove_cover
      = f.check_box :remove_cover
  .actions
    = f.submit "Save"

app/views/items/_item.html.haml
%tr
  %td
    - if item.cover?
      = image_tag item.cover.thumb.url
  %td= link_to item.name, item_path(item)
  %td= item.author
  %td= item.ISBN
  %td= link_to "Edit item", edit_item_path(item)

app/views/items/_items.html.haml
= paginate @items
- if params[:search]
  %br
  %h3 Searching results:
%table.table.table-striped#items_all
  %thead
    %tr
      %th{scope: "col"}
      %th{scope: "col"} Name
      %th{scope: "col"} Author
      %th{scope: "col"} ISBN
      %th{scope: "col"}
  %tbody
    = render @items
= paginate @items

app/views/items/create.js.erb
$('#new_item').remove();
$('#new_link').show();
$('#items_all').append('<%= j render(@item) %>');

app/views/items/edit.html.haml
%h2 Edit item
%div
  %p= link_to "Back to all items", items_path
= render "form"

app/views/items/index.html.haml
%div
  %h2 Items
  = link_to "Add item", new_item_path, id: "new_link", remote: true
#items
  = render 'items'

app/views/items/index.js.erb
$("#items").html("<%= j render("items") %>")

app/views/items/new.html.haml
%h2 Create a new item
%div
  %p= link_to "Show all items", items_path
= render "form"

app/views/items/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>'); 

app/views/items/show.html.haml
%div
  %p= link_to "Add item", new_item_path
  %p= link_to "Show all items", items_path
%div
  %p
    Name: #{@item.name}
  %p
    Author: #{@item.author}
  %p
    ISBN: #{@item.ISBN}
  %p
    Item type: #{@item.item_type}
  - if @item.cover?
    %p= image_tag @item.cover.thumb.url
    %p= link_to "Edit item", edit_item_path
    / # Shows cover itself
    / <p>Cover: <haml_silent></haml_silent></p>
  - else
    %p This item don't have a cover yet, but you can change it!
    %p= link_to "Edit item", edit_item_path

app/views/layouts/_header.html.haml
%header.header
  .container
    %nav
      %ul.nav
        %li.nav-item
          = link_to "Home", root_path, class: 'nav-link active'
        %li.nav-item
          = link_to "About", "#", class: 'nav-link active'
        = render 'layouts/search_form'

app/views/layouts/_search_form.html.haml
%li.nav-item.d-flex
  = link_to "Log in", "#", class: 'nav-link active'
= form_tag(items_path, method: :get, class: 'bd-search d-flex', id: 'items_search') do
  = text_field_tag :search, params[:search], placeholder: "Search...", class: 'form-control ds-input'
  = button_tag(type: 'submit', title: 'Search', class: "btn btn-primary") do
    = fa_icon "search"
  =#%i.fa.fa-search
  =# submit_tag "Search", :name => nil, class: 'btn btn-outline-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Home Library
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = render 'layouts/header'
      %p.notice= notice
      %p.alert= alert
      .container
        = yield